### ISSUE TITLE
maximum depth

### ISSUE THREAD

**Issue by MalteLond** [lorenzha/hdcd#29]
It would be nice if hdcd could be given a max. depth that the tree is allowed to grow. If you don't object I'll propose some code to implement this.

**Comment by lorenzha** [comment]
Go ahead, but the default should be NULL and no action taken since there is no justification for doing this except for computational constraints. However, the changepoints found first might also be the most relevant ones so this might be a direction to look at for further optimizing speed while sacrificing accuracy in finding all changepoints...

**Comment by lorenzha** [comment]
Is implemented in @MalteLond 's upcoming PR
